apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress-resource
  namespace: default
spec:
  rules:
  - host: staging.4k.com
    http:
      paths:
      - backend:
          serviceName: frontend-4k
          servicePort: 3001
        path: /
        pathType: ImplementationSpecific
      - backend:
          serviceName: external-ip
          servicePort: 80
        path: /blog
        pathType: ImplementationSpecific
      
  - host: staging-orders.4k.com
    http:
      paths:
      - backend:
          serviceName: backend-4k
          servicePort: 3000
        path: /
        pathType: ImplementationSpecific
  - host: staging-account.4k.com
    http:
      paths:
      - backend:
          serviceName: account-server4k
          servicePort: 3000
        path: /
        pathType: ImplementationSpecific