apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ezio-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: env.talha.cf
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
                service:
                  name: nginx
                  port:
                    number: 80
  volumeMounts:
    - mountPath: /etc/nginx/template
      name: nginx-template-volume
      readOnly: true
volumes:
  - name: nginx-template-volume
    configMap:
      name: nginx-template
      items:
      - key: nginx.tmpl
        path: nginx.tmpl
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-template
data:
  nginx.tmpl: |
  server {
	listen 80 ;
	listen [::]:80 ;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.nginx-debian.html;

	server_name serkinti.com;

	location / {
		proxy_pass http://youtube.com;
  }
