kind: Namespace
apiVersion: v1
metadata:
  name: summation
  labels:
    name: summation
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: summation-backend
  namespace: summation
spec:
  template:
    metadata:
      name: summation-backend-v1 # revision-naming-convention (name-version)
    spec:
      containers:
        - image: docker.io/talhaabdurrahman/summation-backend:latest
          ports:
            - containerPort: 5000
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: summation-frontend
  namespace: summation
spec:
  template:
    metadata:
      name: summation-frontend-v1 # revision-naming-convention (name-version)
    spec:
      containers:
        - image: docker.io/talhaabdurrahman/summation-frontend:latest
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_URL
              value: "http://summation-backend.summation"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: summation
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent 
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo 'server {
  listen 8081 ;
  listen [::]:8081 ;

  root /usr/share/nginx/html;

  index index.html;

  location / {
    proxy_pass http://summation-backend.summation;
}
}

server {
	listen 8082 ;
	listen [::]:8082 ;

	root /usr/share/nginx/html;

	index index.html;

	location / {
		proxy_pass http://summation-frontend.summation;
}
}' >> /etc/nginx/conf.d/default.conf "]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: summation
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer